Update Footer.jsx
cetav-ddw/lalibertad-cetav pull request #138
Opened 2023-11-10 18:39 UTC by larace

## Description

- Se actualizo el footer con el responsive 

### How to verify this PR

- Para visualizar los cambios se debe cambiar la resolución de la pagina

2023-11-10 18:42 UTC, jleiva requested changes

2023-11-10 18:42 UTC, jleiva commented on src/app/components/Footer.jsx
> +        textAlign={{ base: "center", md: "flex-start" }}
estas centrando el texto para todo, el componente no es flex asi que flext-start no aplica

2023-11-10 19:02 UTC, larace commented on src/app/components/Footer.jsx
> +        textAlign={{ base: "center", md: "flex-start" }}
Ya aplique cambios!!

2023-11-11 03:45 UTC, jleiva commented on src/app/components/Footer.jsx
> +        textAlign={{ base: "center", md: "center", lg: "left" }}
`md` incluye `base`, no hace falta volver a declarar el `center`
```suggestion
        textAlign={{ base: "center", lg: "left" }}
```

2023-11-13 21:07 UTC, jleiva approved these changes

2023-11-13 21:07 UTC, merged