Implementación del menú de hamburguesa
cetav-ddw/lalibertad-cetav pull request #142
Opened 2023-11-10 21:11 UTC by 4Driian

- Se implementa el menú de hamburguesa responsivo y funcional para mobile

![Screenshot 2023-11-10 151059](https://github.com/cetav-ddw/lalibertad-cetav/assets/105097849/112b1b54-4157-4a33-94d1-d4d2c39ec296)

### How to verify this PR

1. ...
2. ...
3. ...

2023-11-11 03:46 UTC, jleiva commented on src/app/components/Header.jsx
>              alt="Triada Logo"
Aqui deberiamos de estar usando el componente `Image`, podes hacer el cambio como parte de este PR porfa

2023-11-11 03:47 UTC, jleiva commented on src/app/components/MainNavigation.jsx
> +import { Box, Link, Drawer, DrawerOverlay, DrawerContent, DrawerCloseButton, DrawerHeader, DrawerBody, IconButton} from '@chakra-ui/react';
podes aseguratre de que se corrio prettier antes, parece que hace falta

2023-11-11 03:48 UTC, jleiva commented on src/app/components/MainNavigation.jsx
> +import { useState } from 'react';
podes mover este import a que sea el primero de todos los imports, porfa

2023-11-11 03:49 UTC, jleiva commented on src/app/components/MainNavigation.jsx
> +        <Drawer placement="left" onClose={onClose} isOpen={isOpen}>
podes extraer todo lo que es la navegacion de movil a un componente aparte porfa

2023-11-11 03:51 UTC, jleiva commented on src/app/components/MainNavigation.jsx
> +            <DrawerHeader>Menú</DrawerHeader>
Que tal si en lugar de que diga Menu, aca ponemos el logo? y ocultamos el otro

2023-11-14 07:17 UTC, 4Driian commented on src/app/components/MainNavigation.jsx
> +              <Box mb={4}>
Tienen que ir dentro de un box, ya que por si mismo el "mb" no los separa o los pone en lista

2023-11-15 04:10 UTC, jleiva commented on src/app/components/Header.jsx
>              height="90px"
podes usar el prop de margin, aqui estas declarando estilos inline al pasarle `style`

<img width="885" alt="image" src="https://github.com/cetav-ddw/lalibertad-cetav/assets/598867/d2f7ae48-8ee6-4a03-9ea5-8688aa57faab">

2023-11-15 04:12 UTC, jleiva commented on src/app/components/MobileNavigation.jsx
> +            {isMobile && (
porque necesitas el isMobile? el wrapper en linea 25 ya setea el display none

2023-11-15 04:14 UTC, jleiva commented on src/app/components/MainNavigation.jsx
> +              <Box mb={4}>
no me parece que sea requerido que vaya dentro del Box, el margin se lo podes poner al Link directo, y para que que esten en stack es cuestion que definas los estilos en DrawerBody

2023-11-15 04:18 UTC, jleiva commented on src/app/components/MainNavigation.jsx
> -        >
un dedazo aqui, removiste Inicio

2023-11-15 04:19 UTC, jleiva requested changes

2023-11-15 04:19 UTC, jleiva commented on src/app/components/MainNavigation.jsx
> +      <MobileNavigation />
MobileNavigation debe estar en Header, no acá, no tienen dependencia uno del otro

2023-11-16 15:27 UTC, jleiva approved these changes

2023-11-16 15:27 UTC, merged