Navigation Active
cetav-ddw/lalibertad-cetav pull request #144
Opened 2023-11-11 19:17 UTC by AndreyrM01

## Description

Agrego el modo activo utilizando Pathname para que indique en cual pagina esta ubicado  

### How to verify this PR

![Captura de pantalla 2023-11-11 131703](https://github.com/cetav-ddw/lalibertad-cetav/assets/106450347/6e475982-302b-4eab-8439-f8d66b3008d3)
![Captura de pantalla 2023-11-11 131711](https://github.com/cetav-ddw/lalibertad-cetav/assets/106450347/0f600740-47ea-416b-a480-18df86588916)

2023-11-13 21:15 UTC, jleiva requested changes

2023-11-13 21:15 UTC, jleiva commented on src/app/components/MainNavigation.jsx
> +      borderBottom={isActive ? '1px solid black' : 'none'}
si vas a usar el border, tenes que quitar underline en hover, de lo contrario aplican los dos y se ve mal

<img width="1010" alt="image" src="https://github.com/cetav-ddw/lalibertad-cetav/assets/598867/8cd5f995-94f2-469f-82c6-ef5690022836">

Para el borde usa dos pixeles y el color #427FDF, en hover ponele el mismo al texto, no borde

<img width="964" alt="image" src="https://github.com/cetav-ddw/lalibertad-cetav/assets/598867/18d4f3eb-ed37-4dee-a39b-ebc63a4feb0d">

2023-11-14 00:48 UTC, AndreyrM01 commented on src/app/components/MainNavigation.jsx
> +      borderBottom={isActive ? '1px solid black' : 'none'}
Ok ya realice los cambios subi 2 distintos ya que no le habia entendido la idea, pero en el que se llama actualizo hover, en este al hacer hover el texto cambia de color y al seleccionarlo se queda el borderBottom

2023-11-14 02:51 UTC, jleiva approved these changes

2023-11-14 02:51 UTC, merged