Eegresados cards box
cetav-ddw/lalibertad-cetav pull request #153
Opened 2023-11-14 23:32 UTC by OxCart00

## Description

### How to verify this PR

Try to use the filters on egresados page

2023-11-15 00:31 UTC, OxCart00 commented
Para probar en local crear un archivo .env en el root y crear la variable con el token (esta en vercel)

2023-11-15 00:33 UTC, fmontes approved these changes

2023-11-15 00:33 UTC, fmontes commented on package.json
> +    "dotenv": "^16.3.1",
No necesitamos `dotenv` nextjs se encarga.

2023-11-15 05:32 UTC, jleiva commented on package.json
> -    "@chakra-ui/icons": "^2.1.1",
removiste icons?

2023-11-15 05:32 UTC, jleiva commented on src/app/components/FilterMenu.jsx
> +import CardEgresadosContainer from './CardEgresadosContainer';
para todos los imports de componentes estamos usando alias, `@/app/components`

2023-11-15 05:32 UTC, jleiva commented on src/app/components/FilterMenu.jsx
> +    timer = setTimeout(fetchData, 1000, carreerList, yearList);
porque necesitamos un setTimeout?

2023-11-15 05:32 UTC, jleiva commented on src/app/components/FilterMenu.jsx
> +      {uniqueRecords.length > 0 && (
hay que poner un loader, esto se va a ejecutar en el cliente, y la seccion va a quedar vacia, y cuando termine el request va a haber un brinco donde se haga el render; si se pudiera usar skeletons mejor

2023-11-15 05:32 UTC, jleiva commented on src/app/components/CareerFilter.jsx
> -          <Icon as={MdKeyboardArrowDown} />
hay que usar Icon, a como estaba, para tener acceso a los props de chakra

2023-11-15 05:32 UTC, jleiva commented on src/app/components/CardEgresadosContainer.jsx
> +          size={isMobile ? 'xs' : 'md'}
aqui podes usar los breakpoints directo, en sintaxis de objeto, igual en los otros lugares donde tenes isMobile

2023-11-15 05:32 UTC, jleiva commented on src/app/components/CardEgresadosContainer.jsx
> +            borderRadius="50%"
revisa el radius, porque no esta redondo

2023-11-15 05:32 UTC, jleiva commented on src/app/components/CardEgresadosContainer.jsx
> +        {currentData.map((record) => (
hay que manejar cuando no hay resultados, si selecciono Web y generacion 2018 no hay datos

<img width="889" alt="image" src="https://github.com/cetav-ddw/lalibertad-cetav/assets/598867/4c7ad8a3-fe99-4df3-ad81-852409db79a5">

2023-11-15 05:32 UTC, jleiva commented on src/app/components/CardEgresados.jsx
> +              <a
usar Link https://chakra-ui.com/docs/components/link/usage#imports

2023-11-15 05:32 UTC, jleiva commented on src/app/components/CardEgresados.jsx
> +                  aria-label="See LinkedIn"
en español, y deberia de ser un texto mas descriptivo, se podria concatenar el nombre y apellido

2023-11-15 05:32 UTC, jleiva commented on src/app/components/CardEgresados.jsx
> +          <Avatar name={user.fields.name} src={user.fields.avatar} />
la foto puede ser un poco más grande, se ve muy pequeno, y podriamos usar 4 columnas, para que haya más espacio, porque los nombres y apellidos estan haciendo salto de linea

2023-11-15 05:33 UTC, jleiva commented
Se va viendo bien 👍🏼

2023-11-16 20:29 UTC, OxCart00 commented on package.json
> -    "@chakra-ui/icons": "^2.1.1",
Fue un mal entendido mío, ya lo volví a agregar

2023-11-16 20:38 UTC, OxCart00 commented on src/app/components/FilterMenu.jsx
> +    timer = setTimeout(fetchData, 1000, carreerList, yearList);
Ese timer lo puse para que se espere un segundo después del ultimo cambio en los filtros, para asegurar que ya se seleccionaron todos los criterios de búsqueda deseados.

2023-11-16 23:54 UTC, jleiva requested changes

2023-11-16 23:54 UTC, jleiva commented on src/app/components/CardEgresados.jsx
> +      style={cardStyle}
esto va a agregar los estilos inline, usa el prop correspondiente

2023-11-16 23:54 UTC, jleiva commented on src/app/components/CardEgresados.jsx
> +      maxW={isMobile ? 'xs' : 'lg'}
usa sintaxis de objeto con los breakpoints, por consistencia con el resto del code base y para no tener que estar revisando que recibio el hook

2023-11-16 23:54 UTC, jleiva commented on src/app/components/CardEgresados.jsx
> +          <Box maxWidth={isMobile ? '50%' : '60%'}>
en general, remove `isMobile` y usa breakpoints

2023-11-16 23:54 UTC, jleiva commented on src/app/components/CardEgresados.jsx
> +                aria-label="Enlace-portafolio-profesional"
no hace falta usar la palabra enlace, y tampoco usar los dash, esto lo anuncia un lector de pantalla, asi que se escribe de manera natural; y creo que lo mencione antes, si vas a usarlo, puede ser más descriptivo, como `Ver perfil en Linkedin de Oscar Corella`, entonces seria como `aria-label={`Ver perfil en Linkedin de ${user.fields.name}`}`, igual para el link al portafolio

2023-11-16 23:54 UTC, jleiva commented on src/app/components/CardEgresadosContainer.jsx
> +  const ITEMS_PER_PAGE = isMobile
aqui si esta bien usar isMobile

2023-11-16 23:54 UTC, jleiva commented on src/app/components/YearbookCards.jsx
> +              {/* Anuario <ExternalLinkIcon mx="2px" /> */}
porque esta comentado?

2023-11-16 23:54 UTC, jleiva commented on src/app/components/YearFilter.jsx
> +        <Flex fontWeight="bold" alignItems='center' justifyContent="space-between">
recorda correr prettier, aca hay un mix de doble y single quotes

2023-11-16 23:54 UTC, jleiva commented on src/app/components/FilterMenu.jsx
> +      {loading && <p>Cargando...</p>}
hay un spinner en chakra listo para usar aca

2023-11-16 23:54 UTC, jleiva commented on src/app/components/FilterMenu.jsx
> +      <div style={{ textAlign: 'center', marginTop: '50px' }}>
un Box en lugar de div

2023-11-16 23:54 UTC, jleiva commented on src/app/components/FilterMenu.jsx
> +      {!loading && uniqueRecords.length === 0 && <p style={{ fontWeight: 'bold', fontSize: '1.5em' }}>No hay resultados.</p>}
Text en lugar de p

2023-11-16 23:54 UTC, jleiva commented on src/app/components/FilterMenu.jsx
> +    timer = setTimeout(fetchData, 1000, carreerList, yearList);
entiendo, pero hay que cambiar esa implementacion entonces porque estamos alentisando la funcionalidad; el problema es como hicieron el UI, si quieren esperar a que más de una opcion este seleccionada, no deberian de tener la accion en el click del elemento, una alternativa seria tener algun boton al final de las opciones y que las opciones sean checks, asi solo se hace el filtro de manera explicita cuando termine de seleccionar

2023-11-17 22:06 UTC, jleiva commented on src/app/components/CardEgresados.jsx
> +                  aria-label={`Ver perfil en Linkedin de: ${user.fields.name}`}
esto es el portafolio, no linkedin

2023-11-21 17:30 UTC, jleiva commented on src/app/components/CardEgresadosContainer.jsx
> +          size={isMobile ? 'xs' : 'md'}
@OxCart00 hacer este cambio en el siguiente PR

2023-11-21 17:31 UTC, jleiva commented on src/app/components/FilterMenu.jsx
> +import CardEgresadosContainer from './CardEgresadosContainer';
@OxCart00 aplicarlo en el siguiente PR

2023-11-21 17:31 UTC, jleiva approved these changes

2023-11-21 17:33 UTC, merged